# Generated by Django 4.2.5 on 2023-09-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='salesforecast',
            options={'verbose_name': 'Спрос', 'verbose_name_plural': 'Спрос'},
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='product',
            name='st_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stores'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='st_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stores'),
        ),
    ]
