# Generated by Django 4.2.5 on 2023-09-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('pr_sku_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='id товара')),
                ('pr_group_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='Группа товара')),
                ('pr_cat_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='Категория товара')),
                ('pr_subcat_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='Подкатегория товара')),
                ('pr_uom_id', models.IntegerField(null=True, unique=True, verbose_name='Маркер')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('st_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='id магазина')),
                ('st_city_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='id города')),
                ('st_division_code', models.CharField(max_length=50, null=True, unique=True, verbose_name='id дивизиона')),
                ('st_type_format_id', models.IntegerField(null=True, unique=True, verbose_name='id формата магазина')),
                ('st_type_loc_id', models.IntegerField(null=True, unique=True, verbose_name='id тип локации/окружения магазина')),
                ('st_type_size_id', models.IntegerField(null=True, unique=True, verbose_name='id типа размера магазина')),
                ('st_is_active', models.BooleanField(null=True, verbose_name='Флаг активного магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('target', models.IntegerField(default=0, verbose_name='Спрос в шт')),
                ('pr_sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
                ('st_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stores')),
            ],
            options={
                'verbose_name': 'Спрос',
                'verbose_name_plural': 'Спрос',
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('pr_sales_type_id', models.BooleanField(null=True, verbose_name='Промо')),
                ('pr_sales_in_units', models.FloatField(null=True, verbose_name='Продажи без промо в шт.')),
                ('pr_promo_sales_in_units', models.FloatField(null=True, verbose_name='Продажи с промо в шт.')),
                ('pr_sales_in_rub', models.FloatField(null=True, verbose_name='Продажи без промо в РУБ')),
                ('pr_promo_sales_in_rub', models.FloatField(null=True, verbose_name='Продажи с промо в РУБ')),
                ('pr_sku_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categories')),
                ('st_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stores')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
