# Generated by Django 4.2.5 on 2023-09-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdata',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
    ]
