# Generated by Django 4.2.5 on 2023-10-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Дата")),
                ("holiday", models.BooleanField(null=True, verbose_name="holiday")),
            ],
            options={
                "verbose_name": "holiday",
                "verbose_name_plural": "holiday",
            },
        ),
        migrations.AlterField(
            model_name="salesforecast",
            name="target",
            field=models.PositiveIntegerField(default=0, verbose_name="Спрос в шт"),
        ),
    ]
