# Generated by Django 4.2.5 on 2023-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_salesdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='pr_cat_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='pr_group_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Группа товара'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='pr_subcat_id',
            field=models.CharField(max_length=50, null=True, verbose_name='Подкатегория товара'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='pr_uom_id',
            field=models.IntegerField(null=True, verbose_name='Маркер'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='st_city_id',
            field=models.CharField(max_length=50, null=True, verbose_name='id города'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='st_division_code',
            field=models.CharField(max_length=50, null=True, verbose_name='id дивизиона'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='st_type_format_id',
            field=models.IntegerField(null=True, verbose_name='id формата магазина'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='st_type_loc_id',
            field=models.IntegerField(null=True, verbose_name='id тип локации/окружения магазина'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='st_type_size_id',
            field=models.IntegerField(null=True, verbose_name='id типа размера магазина'),
        ),
    ]
